### ISSUE TITLE
Change color icons based on state?('on' or 'off')

### ISSUE THREAD

**Issue by Kinnoon** [junalmeida/homeassistant-minimalistic-area-card#10]
1. Can you add support for Change color icon when entity state change ?

and
2. Possibility to change from tap/click(hold) to tap/click entity to see detailed information

**Comment by junalmeida** [comment]
I will take this into consideration, however I believe you currently can achieve this with https://github.com/Mariusthvdb/custom-ui

**Comment by kauelima** [comment]
+1 Just found this card and would love this feature. For light entities, it's great to have them yellow when on or even color matching the color of the light.

**Comment by junalmeida** [comment]
> +1 Just found this card and would love this feature. For light entities, it's great to have them yellow when on or even color matching the color of the light.

Doesn't custom ui template glob do this job on any card?

**Comment by kauelima** [comment]
> Doesn't custom ui template glob do this job on any card?

This adds an external dependency. It can work, but the ideal would be to have those main features baked in. I think custom colors are in fact something that can be left for external customization, but the stardand yellow for lights when on is something that the custom component should do by default.

**Comment by junalmeida** [comment]
I will take it into consideration; however, my initial intent is to keep this card minimalist, and if I add this feature, it will only be effective within the card itself. 

The https://github.com/Mariusthvdb/custom-ui would make your entities work across all HA with minor effort like: 

```yaml
customize_glob:
  "light.kitchen_*":
    templates:
       icon_color: if (state === 'on') return 'yellow'; return 'white';
``` 

My advice is to try `custom-ui` as it may be a ready-to-use solution for you. It may take some time for me to prioritize feature requests but I appreciate you sharing your thoughts here, thx :)

**Comment by ibins1980** [comment]
Hallo ich habe custom-iu probiert aber es funktioniert bei mir nicht. Gibt es eine andere möglichkeit die Farbe zu ändern?

Danke und Gruß Danny

`customize_glob:
  "light.*":
    templates:
       icon_color: if (state === 'on') return 'yellow'; return 'white';`

**Comment by junalmeida** [comment]
@ibins1980 The only way today is custom-ui. Please double check if it is installed and properly running. 

Please try one of the basic examples from the component to see if it is working:
https://github.com/Mariusthvdb/custom-ui

**Comment by zazu-sf** [comment]
+1
