### ISSUE TITLE
[Question]: Show no Entity at all?

### ISSUE THREAD

**Issue by lxffm** [junalmeida/homeassistant-minimalistic-area-card#106]
### What happened?

Hey there,

anyone around who can help me, as I want to have entity at all being shown on the card. If I remove all entities, it just shows all entities.

Sometimes, I don't have anything valuable in that room to show on that card, but I'm using them as headers or simply as a beautiful navigation Button to Rooms or Zones.

Any idea?

### Card Version

1.2.0

### HomeAssistant Version

2024.8.2

**Comment by LesTR** [comment]
@lxffm what about `entities: []` ?

**Comment by lxffm** [comment]
> @lxffm what about `entities: []` ?

That works! You are awesome. What does [] that mean? I've tried null and none but that didn't work

**Comment by LesTR** [comment]
`[]` it's empty array/list

**Comment by lxffm** [comment]
Thank you very much, for the swift help!
