### ISSUE TITLE
[Question]: Add climate status and + and - button to increase or decrease temperature ?

### ISSUE THREAD

**Issue by Frazou1** [junalmeida/homeassistant-minimalistic-area-card#108]
### What happened?

Add climate status and + and - button to increase or decrease temperature at the sensor level under the name of the room.

### Card Version

1.2.0

### HomeAssistant Version

2024.11.01

**Comment by junalmeida** [comment]
Sorry I don´t think this project should have the objective of being multiple type of cards. You can use thermostat cards for that.
