### ISSUE TITLE
Set card height

### ISSUE THREAD

**Issue by TheWhiteGandalf** [junalmeida/homeassistant-minimalistic-area-card#17]
My wish to improve card height would be to define a card height. 
Thanks for your great lovelace card :-)

**Comment by junalmeida** [comment]
I'm not sure if this is possible as typically cards follow its container height. I've never seen any HA card that sets its own height. You could direct me if you know any.

**Comment by ImagineerNL** [comment]
@junalmeida : Other than card-mods or custom-css routes, there is the grid-card which has the 'squares' option to enable/disable.
Perhaps this helps in a bit more flexibility in setting heights.

another option would be to allow entities to show on multiple lines, which in itself would change the height as well

https://www.home-assistant.io/dashboards/grid/

**Comment by szemod** [comment]
See this card as example:
type: custom:mini-graph-card
height: 241

**Comment by junalmeida** [comment]
@szemod My goal here is to not go on practices HA devs won't go. Since I don't see any native card customizing height, I wouldn't go that path. 
However I will take a look at @ImagineerNL 's suggestion about the "square" attribute of native cards.
