### ISSUE TITLE
Support for Area image

### ISSUE THREAD

**Issue by elupus** [junalmeida/homeassistant-minimalistic-area-card#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Make use of standard home assistant area image.

**Describe alternatives you've considered**

**Additional context**
See screenshots from #3

**Comment by zSprawl** [comment]
It would be cool to be able to toggle all items in an area to be included, and then just exclude stuff, but that might be a lot to ask.

**Comment by junalmeida** [comment]
@zSprawl you may open a specific ticket to track your request, as this one is related to the image only.

**Comment by groenmarsmannetje** [comment]
This probably could be done by assigning the area to this card and then make use of that image.

**Comment by smenzer** [comment]
the new default [Area card](https://www.home-assistant.io/dashboards/area/) also supports using a camera image, which would be a great addition here!
