### ISSUE TITLE
tap_action support

### ISSUE THREAD

**Issue by gfandrea** [junalmeida/homeassistant-minimalistic-area-card#2]
**Is your feature request related to a problem? Please describe.**
I am using my current area card to navigate to the relative pages

**Describe the solution you'd like**
Could it be possible to add a "tap_action"? Maybe on the title?

**Comment by gminco** [comment]
I second this! I'd love to replace the cards I'm using with this but I need to be able to at least click on the title or upper section of the card to be able to navigate to another page.

**Comment by junalmeida** [comment]
Yes a `tap_action` is on my wishes. I will do it as soon as I have a spare time :) 
Thanks for using it :)
