### ISSUE TITLE
Doesn’t work in horizontal-stack with more than one sensor (depending on screen size)

### ISSUE THREAD

**Issue by superpower10** [junalmeida/homeassistant-minimalistic-area-card#20]
Card doesn’t work in horizontal-stack with more than one sensor (see screenshot)
![5759CA48-AAAC-4D73-B12A-8F62EAF17C68](https://user-images.githubusercontent.com/20533966/172772600-ecde2b1f-6eda-48c8-979b-d1412efd826c.jpeg)
![2F330B3E-5752-464A-AA23-74C3D8C91020](https://user-images.githubusercontent.com/20533966/172772869-3b4e3f89-4c90-43f3-8e89-1c7b172205fa.jpeg)

**Comment by junalmeida** [comment]
Currently this version does not support too many information sensors. I'm not sure how I would "fix" that. 
Only action entities are supposed to break lines at this moment. 

I will try to think how I should tackle this. 

Thx
