### ISSUE TITLE
[Request]: show entity attribute?

### ISSUE THREAD

**Issue by Csstenersen** [junalmeida/homeassistant-minimalistic-area-card#23]
### What happened?

Can you make it possible to show entity attribute in the card?

### Card Version

1.0.6

### HomeAssistant Version

2022.6.2

**Comment by junalmeida** [comment]
I will take it under consideration, thx

**Comment by junalmeida** [comment]
I think it is already possible to show an attribute, please see: 
https://www.home-assistant.io/dashboards/entities/#special-row-elements

`attribute` property
