### ISSUE TITLE
[Enhancement]: Change text color in config

### ISSUE THREAD

**Issue by smenzer** [junalmeida/homeassistant-minimalistic-area-card#26]
### What happened?

The text is always white, but with some backgrounds that's not the best looking color. It would be great to be able to set a text color the same way you can with background_color

### Card Version

1.0.6

### HomeAssistant Version

2022.11.5

**Comment by junalmeida** [comment]
You could try customize the theme or the card itself using custom-ui.

**Comment by junalmeida** [comment]
Color is the same of `ha-picture-card-text-color`, it can be customized via a theme
