### ISSUE TITLE
[Bug]: Camera images appear with incorrect aspect ratio/do not fill card

### ISSUE THREAD

**Issue by cerebrate** [junalmeida/homeassistant-minimalistic-area-card#33]
### What happened?

When using a camera_image referencing the snapshots taken by my Ring cameras, the image only partially fill the card, thus:

![image](https://user-images.githubusercontent.com/371623/209450635-7603f67f-d8a1-4260-9427-1069dade2b84.png)

Expected: card-filling image.

(I see this has also been noted by @jlaska, here: https://github.com/junalmeida/homeassistant-minimalistic-area-card/issues/6#issuecomment-1364540323)

### Card Version

1.0.6

### HomeAssistant Version

2022.12.8

### Relevant javascript log output

```shell
No relevant log output was seen.
```

**Comment by junalmeida** [comment]
Thanks for reporting, I also have noticed this.

**Comment by junalmeida** [comment]
A release will appear shortly in HACS

**Comment by cerebrate** [comment]
Works great now, thanks.
