### ISSUE TITLE
[Bug]: too many sensor entities don't wrap

### ISSUE THREAD

**Issue by smenzer** [junalmeida/homeassistant-minimalistic-area-card#34]
### What happened?

If there are too many entities that are put in the top row, they extend outside of the area card instead of wrapping (like the control entities below do). See the screenshot for an example of what I mean (note - I duplicated a set of entities just to get the number of entities high enough to cause the issue).

<img width="617" alt="image" src="https://user-images.githubusercontent.com/624392/209458462-e26fe675-d2a8-463c-8816-1032651073e1.png">

I would expect that the sensor entities wrap to the next row (left aligned).

### Card Version

1.1.2

### HomeAssistant Version

2022.12.6

### Relevant javascript log output

```shell
n/a
```

**Comment by junalmeida** [comment]
Yep this is a known bug, and at this moment I don't see a quick way to fix it other than simply not having that much amount of entities. So I suggest to separate into two cards if you need all those sensors, or remove the least useful ones.
