### ISSUE TITLE
[Enhancement]:  custom height for card

### ISSUE THREAD

**Issue by smenzer** [junalmeida/homeassistant-minimalistic-area-card#35]
### What happened?

I love how space efficient the cards are...however it's quite short and so the images of my areas are almost too small to make them useful. It would be great if we could set a custom height for the card to give a bit more room when needed.

**Current:**
<img width="534" alt="image" src="https://user-images.githubusercontent.com/624392/209458515-44fa7639-7dd6-4bff-a700-cb5f988aa617.png">

**A slightly larger height just makes my images a bit easier to see:**
<img width="520" alt="image" src="https://user-images.githubusercontent.com/624392/209458600-6b171cce-04d3-4d20-9488-f7cb0a3c4673.png">

Seems like adding a custom height to the `minimalistic-area-card` or the `ha-card` would do the trick (but I didn't investigate much more than playing in dev tools).

### Card Version

1.1.2

### HomeAssistant Version

2022.12.6

### Relevant log output

```shell
n/a
```

**Comment by sortilego** [comment]
This would be great! In the meantime @smenzer can you help to increase the height of the tiles? I tried to modify the ha-card section in the js file but nothing changed. Thanks

**Comment by junalmeida** [comment]
A min-height can now be specified for the sensors area, using a theme:
```yaml
minimalistic-area-card-sensors-min-height: 50px
````

**Comment by smenzer** [comment]
@junalmeida thanks for all the updates today! quick question - if I'm already using a theme on my dashboard (e.g. Mushroom square), how would I go about setting the `minimalistic-area-card-sensors-min-height` value some place? do I have to just copy the existing theme's yaml file to a new file name (e.g. `my-custom-mushroom-square.yaml`) and then add the value there? the downside is that any updates to the normal Mushroom square theme would need to be copied over, but I suppose that's not a huge deal, but wanted to check if there was an easier way you'd recommend. thanks!

**Comment by francais01** [comment]
I added this to the `custom:minimalistic-area-card`:
```
card_mod:
  style: |
    ha-card {
      --minimalistic-area-card-sensors-min-height: 100px;
    }
```

**Comment by smenzer** [comment]
ah that's perfect...i knew there was an easy way to do this! thank you @francais01!
