### ISSUE TITLE
[Bug]: Text is not on the same height as Icon

### ISSUE THREAD

**Issue by superpower10** [junalmeida/homeassistant-minimalistic-area-card#36]
### What happened?

The Text is always higher than the icon 

![28E43339-A17C-4802-BCE4-40B369F3E2F4](https://user-images.githubusercontent.com/20533966/209723766-7d1cb5af-7398-4e38-ad46-386fb1180966.jpeg)

### Card Version

1.1.2

### HomeAssistant Version

2022.12.8

**Comment by junalmeida** [comment]
Yep that happens in some sizes. Thanks for reporting

**Comment by junalmeida** [comment]
I noticed that you also miss the rounded corners, and the text size is greater than what I have specified. What browser are you using?

**Comment by superpower10** [comment]
Updates fixed it. Thank you very much. 

(I’m using iOS Home Assistant App)
