### ISSUE TITLE
[Bug]: Custom element doesn't exist : minimalistic-area-card in Android Companion App

### ISSUE THREAD

**Issue by reglisse69** [junalmeida/homeassistant-minimalistic-area-card#46]
### What happened?

Hello.

Thank you for this awesome card, discovered yesterday... 

Done some work to build a minimalist view very quickly and easily.
No problem on desktop browser (Chrome/Firefox with internal or external URL) but in Android Companion App, got "Custom element doesn't exist : minimalistic-area-card", even with a clean dashboard and a simplist card.

Doesn't seems to be related to external URL.

No problem with other HACS frontend components.

### Card Version

1.1.8

### Home Assistant Version

HA 2023.1.0 / Supervisor 2022.12.1 / OS 9.4

### Browser Version

Home Assistant Android Companion App 2022.12.0

### Relevant javascript log output

```shell
Not found
```

**Comment by junalmeida** [comment]
If you just added, your companion app might be in cache. Try clearing its cache. There is no specific code that runs on companion apps only.

**Comment by reglisse69** [comment]
Hi, sorry, it was indeed a cache problem. Solved after a restart of my phone.
Regards?

**Comment by reglisse69** [comment]
Hi, sorry, it was indeed a cache problem.
Solved after a restart of my phone.

Regards.
