### ISSUE TITLE
[Question]: Size of cards and space between cards has changed after installing custom ui

### ISSUE THREAD

**Issue by Zipp0KMS** [junalmeida/homeassistant-minimalistic-area-card#47]
### What happened?

Size of cards and space between cards has changed after installing custom ui.
The icons are in an other position and the cards are bigger.
![Screenshot_20230110_093351_Home Assistant](https://user-images.githubusercontent.com/97192615/211502354-2c689048-7332-4245-a706-a0cef81136b5.png)

### Card Version

1.1.8

### HomeAssistant Version

2022.12.6

**Comment by junalmeida** [comment]
I don't see how I can help you there with no information. It seems your setup also affected other cards based on the screenshot, so this might be a question to custom-ui, or maybe check the current theme you have in place. Or remove custom-ui if you don't need it. Custom-ui is not part of this project.

**Comment by Zipp0KMS** [comment]
Thanks for you quick reply. 
I didn't config something with custom ui, just installed. custom ui was suggested in another question and I wanted to test it. 
I will examine the theme. thanks

**Comment by junalmeida** [comment]
@Zipp0KMS yep, once you have more information, if you still need help feel free to reopen the question. Thx :)
