### ISSUE TITLE
[Feature Request]:  Color and intensity of Entity Icon when turned on

### ISSUE THREAD

**Issue by superpower10** [junalmeida/homeassistant-minimalistic-area-card#48]
### What happened?

If an light entity is on its hardly visible. It would be great if the color and intensity of that could be set.

### Card Version

1.1.8

### HomeAssistant Version

2023.1.2

**Comment by junalmeida** [comment]
I'm not sure I can proceed with this request, as this card uses the native home assistant widgets to display icons colors and intensity. 
There is already a `shadow` option for cases where the image chosen brightness is not good with current color and intensity of the light.
