### ISSUE TITLE
[Bug]: Climate entity always placed first

### ISSUE THREAD

**Issue by clinta** [junalmeida/homeassistant-minimalistic-area-card#49]
### What happened?

Other entities seem to show up in the order listed, but a climate entity always ends up first in the inputs, no matter where it is in the `entities` list.

### Card Version

v1.1.8

### Home Assistant Version

2023.1.4

### Browser Version

Brave 1.47.171

**Comment by junalmeida** [comment]
The current code was not written to show entities in order. If you see them in order, it is a coincidence.
