### ISSUE TITLE
[Feature request]:

### ISSUE THREAD

**Issue by FragMenthor** [junalmeida/homeassistant-minimalistic-area-card#51]
### What happened?

Add option to exclude unavailable entities
ex:
```
exclude_unavailable: true
```
ou some kind of filter option.
Thanks, great card!
FragMenthor

### Card Version

1.1.8

### HomeAssistant Version

2023.1.7

**Comment by junalmeida** [comment]
https://github.com/junalmeida/homeassistant-minimalistic-area-card/blob/2cfb4b96d62e2634eed4093faffedc62a12687b4/src/types.ts#L18

It is already there on the current version. I will improve the documentation then.
