### ISSUE TITLE
[Bug]: Null for entities sometimes doesn't work

### ISSUE THREAD

**Issue by laczkodaniel** [junalmeida/homeassistant-minimalistic-area-card#56]
### What happened?

I configured the card for multiple rooms and for some rooms I didn't want to show any entities on the card. Out of 3 rooms it only works for 2. The exact same config doesn't work for the 3rd room for some reason.

Screenshots:

![bedroom_null](https://user-images.githubusercontent.com/65763641/219408992-8852bf06-a340-47bf-a1e1-ecc9a2831dc0.png)
![bathroom_null](https://user-images.githubusercontent.com/65763641/219409018-d25ffeea-cdbe-4675-a8b7-8677da31d2c3.png)

### Card Version

1.1.8

### Home Assistant Version

2023.2.5

### Browser Version

Chrome 109.0.5414.120

**Comment by junalmeida** [comment]
Setting it to `null` is not a scenario I expect at this moment. You can either remove it, or set up a list. Since this is an Area card, if you don't specify an entity list it will automatically grab your area entities. This card is not meant to be empty at this moment.

**Comment by laczkodaniel** [comment]
Thank you for the info.
It would be great to have this feature implemented, as it is a valid use case to not show any entities on the card.
I will create a pull request for this.
