### ISSUE TITLE
[Question]: Can change entity color when state change

### ISSUE THREAD

**Issue by Alarisco** [junalmeida/homeassistant-minimalistic-area-card#57]
### What happened?

Can you add option to set custom color in when a entity is ON or OFF

### Card Version

1.1.8

### HomeAssistant Version

2023_2_5

**Comment by junalmeida** [comment]
Not really. This component uses Home Assistant's native icon buttons to render each entity. However, any customization you can do to native's controls you can also achieve here. Take a look at "custom-ui"/"card-mod".

**Comment by Alarisco** [comment]
OK, TX
