### ISSUE TITLE
[Question]: Possibility to integrate the new (2023.3) Display precision

### ISSUE THREAD

**Issue by joakimjalden** [junalmeida/homeassistant-minimalistic-area-card#59]
### What happened?

Love the card and have used it since pretty much when I started using HA. If you have the possibility to integrate the new (2023.3) "Display precision" when displaying sensor values, that would make it even better.

I looked at the code for the mushroom cards (which included this recently in the v2.6.0 update), and it seems to be there as an attribute ( e.display_precision) for the entity object. My javascript knowledge is, however, too poor to help out with implementation. The precision is not, as far as I can tell, exposed as an entity attribute in the templating engine.

### Card Version

1.1.8

### HomeAssistant Version

2023.3

**Comment by seanw18** [comment]
+1 on both the thanks for the great card, and desire for display precision..

**Comment by Nurgus** [comment]
Definitely much needed. My temperature is currently displaying with 5 decimal places and looks a bit mad.

**Comment by aicarmic** [comment]
+1 for this FR, have the same issue with values taking up precious real estate with 5 decimals. 

It's not the best workaround but if this is bugging you, you can always create a template sensor that trims the extra decimals.

**Comment by MacrosorcH** [comment]
@junalmeida +1 here! Any chance to have proper display precision support implemented? 
It would grately help in cases like the following, where the precision of the temperature sensors is correctly set to 1 in entity settings but the card is displaying 2 or 3 decimals regardless. Thanks! 
![Screenshot_2023-08-06-16-11-32-58_c3a231c25ed346e59462e84656a70e50](https://github.com/junalmeida/homeassistant-minimalistic-area-card/assets/17884387/21ea2770-9555-43e6-8b0e-73e25406d0b8)

**Comment by FvanEgmond** [comment]
@junalmeida I love your card and am using it centrally to show and navigate the rooms in my house. We all understand you are busy, but the last release is from 11 months ago. Do you have time planned in the coming period to fix this and other minor issues maybe? Currently I do display (average) values on the card that show over 10 decimals due to this issue, so a fix for this would be greatly appreciated. 
Keep up the good work, and thanks for your efforts. Cheers!

**Comment by junalmeida** [comment]
Yep I'm very busy but I will try to fix that as it seems its been a problem for many people.

**Comment by junalmeida** [comment]
Forgot to close this, the release https://github.com/junalmeida/homeassistant-minimalistic-area-card/releases/tag/v1.2.0 went live on May 2.
