### ISSUE TITLE
Use Camera Entity as background image.

### ISSUE THREAD

**Issue by TKpizza** [junalmeida/homeassistant-minimalistic-area-card#6]
Can you add support for using a Camera Entity as background image like in the home assistant area card?

**Comment by junalmeida** [comment]
I will think about it, thanks for your suggestion :)

**Comment by diothar** [comment]
Any word? This would replace so many of my cards I’d I could have my Camera in this area view

**Comment by junalmeida** [comment]
@diothar I will take it into consideration, just haven't had time yet to work on it. I would add the feature closest to the way other HA native cards have it (from the user's perspective) , so Pull Request is welcome.

**Comment by zSprawl** [comment]
This would basically make this card superior in every way to the built in area card. Please consider. Thank you!!

**Comment by jlaska** [comment]
I use the following javascript snippet to embed a camera entity image on a custom button-card.  Not sure how, but is it possible to support javascript for the `image` attribute to allow something like the following?

```javascript
      [[[
        return (typeof entity !== 'undefined') ? html`
          <hui-image
            .hass=${hass}
            .cameraImage=${entity.entity_id}
            .entity=${entity.entity_id}
            .cameraView="auto"
            .width="100%"
          ></hui-image>` : ``;
      ]]]
```

**Comment by johnneerdael** [comment]
Fully share above sentiment, I have to areas (front porch and garden) and this card would be my absolute go to when the camera image or even camera snapshots could be used

**Comment by jlaska** [comment]
Thanks for the update @junalmeida!  I'm having trouble getting the sizing/aspect_ratio to display like the area_card.  Will continue playing.

@pticavorobey from the diff, it appears you need to add a `camera_entity: camera.this_is_my_camera` when using the card.

**Comment by jlaska** [comment]
@pticavorobey apologies, misread the PR ... it's `camera_image` not `camera_entity`.
