### ISSUE TITLE
Use of `state_color` is not following behavior of native HA Glance card 

### ISSUE THREAD

**Issue by junalmeida** [junalmeida/homeassistant-minimalistic-area-card#61]
oh.. sorry yes i mean Sensors. Lights and Switches are working with colors! 

But I have found an Button with no color. In Ha the Covers are blue when closed and purple when open. In your Card only white. 
![image](https://user-images.githubusercontent.com/57588422/228550134-2b95ae75-2fa2-4fb9-b7db-c428305ae712.png)
![image](https://user-images.githubusercontent.com/57588422/228550463-4431c726-1678-435a-94e5-5485f074bd6f.png)

![image](https://user-images.githubusercontent.com/57588422/228558471-a2f9904a-b69e-4720-85ed-73a6b91f2a12.png)

_Originally posted by @novus84 in https://github.com/junalmeida/homeassistant-minimalistic-area-card/issues/60#issuecomment-1488594468_

**Comment by novus84** [comment]
thank you so much!! it work now perfectly!! i will send you some Coffee :D
