### ISSUE TITLE
[Bug]: Performance drop since 2023.4.0 update

### ISSUE THREAD

**Issue by Remko76** [junalmeida/homeassistant-minimalistic-area-card#67]
### What happened?

I updated to the latest 2023.4.0 update running on a NUC in a docker environment. I have one page setup with 13 instances of this fantastic card which has been running for half a year now.
Ever since the latest update, the dashboard is completely unresponsive on the mobile app or on a mobile browser. I have tried to simply recreate the dahsboard card by card and found that adding more than 6 cards starts causing this issue.
I have tried about anything I can, but am stuck and cannot use the dashboard like this anymore.

Anyone else experiencing this issue?

### Card Version

1.1.11

### Home Assistant Version

2023.4.0

### Browser Version

Companian App on iOs and latest chrome and safari browser

**Comment by JoepWi** [comment]
I experience the same issue. Running the dashboard on my iPhone 12 Pro (see image) is unresponsive or lags terrible. If I fully close the HA app on my phone sometimes it's possible to interact with the dashboard. But as soon as re-open it it's unresponsive again.
![Scherm­afbeelding 2023-04-07 om 08 30 32](https://user-images.githubusercontent.com/87470267/230554761-f42d5d3c-77aa-4293-a0f1-40cede42a779.png)

I'm afraid I have to abandon the Card

**Comment by Remko76** [comment]
I tried a lot now and figured out the performance issue is caused by having entities displayed in the cards. If I remove all the entities, performance is ok and I can use the cards to navigate again without issues.

So it has something to do with the entities on the cards, but I cannot find out anything more.

**Comment by JoepWi** [comment]
The strange thing is that on my laptop the card performs as usual.

**Comment by Remko76** [comment]
Yes, same here. The issue is only visible on a mobile device. Both the companion app as well as any of the known browser on android and iOS, show the issue.
Everything fine on a laptop though.

**Comment by tamasboldog** [comment]
Same here on iPhone 12 Pro Max. OSX and Safare has the same issue, but it handles it slightly better because of the stronger CPU I assume. iPad pro is the same as OSX. It works, but slowly. Andoid look fine.

This is why I think this is something with Safari.

**Comment by novus84** [comment]
some here is the problem still present in 2023.4.1?

**Comment by balronu** [comment]
The Problem ist still present in2023.4.1 and 2023.4.2

**Comment by junalmeida** [comment]
Could you all please let me know if you are listing entities manually, or using the automatic area entity selection (by having no `entities:` node in config) 

It is weird as this card has no significant change when `2023.4.0` arrived.

**Comment by joakimjalden** [comment]
I have an 8 card setup. Oddly enough my experience seems to be somewhat opposite to previous posts. In the iOS HA app, in Edge on Windos, and Chrome both on Windows and MacOS it runs fine, but on Safari in MacOS it grinds to a halt. 
![1D24B686-AAA7-4B98-9A41-59E0B91C8DFC](https://user-images.githubusercontent.com/3828974/231212850-5c64e25a-42c6-4543-9146-2ab5d530e125.jpeg)

**Comment by Remko76** [comment]
I had the entities listed manually. Also it were only about 3 to 4 per card. Things like door status, lights. But nothing special actually

**Comment by JoepWi** [comment]
> Could you all please let me know if you are listing entities manually, or using the automatic area entity selection (by having no `entities:` node in config) 
> 
> 
> 
> It is weird as this card has no significant change when `2023.4.0` arrived.

I listen to individual entities.

**Comment by joakimjalden** [comment]
Same here. I have the entities listed manually. At most 5 per card at the moment (as seen above).

**Comment by junalmeida** [comment]
It is weird, I have 16 cards, some with 4 or 5 entities listed, and I've never seen any performance issue. I'd like to also know if this may be a conflict with other custom cards/ui (card-mod, custom ui, etc).

Maybe try to isolate the problem by creating a test dashboard.

**Comment by novus84** [comment]
do you use ios?

**Comment by junalmeida** [comment]
I don't, Android only here. I can't really test on iOS.

**Comment by mac-lucky** [comment]
individual entities

**Comment by novus84** [comment]
i have this issue only on iOS, strange thing... iPad OS seems to be ok. But my iPhone (14 Pro Max) had slowdowns in the HA App and in Safari. Nothing works for me then. No menu.. nothing. 

On my Fold everything works as usual.

**Comment by Remko76** [comment]
> It is weird, I have 16 cards, some with 4 or 5 entities listed, and I've never seen any performance issue. I'd like to also know if this may be a conflict with other custom cards/ui (card-mod, custom ui, etc).
> 
> Maybe try to isolate the problem by creating a test dashboard.

I did all that. Started from scratch, basically copying the yaml code card by card and started noticing the issue after I added about 6 cards. Took the entities off and everything ok.
I am using iOS but find the issue using the app, chrome mobile browser. Same on Android actually. So I cannot link it to Safari...

**Comment by joakimjalden** [comment]
> It is weird, I have 16 cards, some with 4 or 5 entities listed, and I've never seen any performance issue. I'd like to also know if this may be a conflict with other custom cards/ui (card-mod, custom ui, etc).
> 
> Maybe try to isolate the problem by creating a test dashboard.

I've also reduced it to a test dashboard with only the minimalistic-area-card, and no card-mod's. As before, the problem only manifests itself for me on the Safari browser on MacOS, not Chrome on the same computer or on iOS on an iPhone13. With only one chad in the test dashboard, the problem is barely noticeable, but when duplicating the same card to six copies the dashboard gets very slow. Also, at six cards the cards stop registering clicks on entities and treat them instead as long presses bringing up the entity info dialog.

**Comment by joakimjalden** [comment]
> > It is weird, I have 16 cards, some with 4 or 5 entities listed, and I've never seen any performance issue. I'd like to also know if this may be a conflict with other custom cards/ui (card-mod, custom ui, etc).
> > Maybe try to isolate the problem by creating a test dashboard.
> 
> I did all that. Started from scratch, basically copying the yaml code card by card and started noticing the issue after I added about 6 cards. Took the entities off and everything ok. I am using iOS but find the issue using the app, chrome mobile browser. Same on Android actually. So I cannot link it to Safari...

I can confirm that taking the entities away also removes the slowdown for me.

**Comment by JoepWi** [comment]
> > > It is weird, I have 16 cards, some with 4 or 5 entities listed, and I've never seen any performance issue. I'd like to also know if this may be a conflict with other custom cards/ui (card-mod, custom ui, etc).
> 
> > > Maybe try to isolate the problem by creating a test dashboard.
> 
> > 
> 
> > I did all that. Started from scratch, basically copying the yaml code card by card and started noticing the issue after I added about 6 cards. Took the entities off and everything ok. I am using iOS but find the issue using the app, chrome mobile browser. Same on Android actually. So I cannot link it to Safari...
> 
> 
> 
> I can confirm that taking the entities away also removes the slowdown for me.

I did the same.

**Comment by joakimjalden** [comment]
The following minimal example is enough to cause a significant slowdown on Safari (Version 16.3) on my 2,4 GHz Intel Mac (MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports, macOS Monterey version 12.6.3) if I have 20 of these cards on a test dashboard. There is also a slowdown with fewer cards, but not all that noticeable. I'm running Home Assistant core-2023.4.2, Home Assistant OS 9.5, on a Home Assistant Blue Odroid.

```
type: custom:minimalistic-area-card
entities:
  - entity: sun.sun
```

**Comment by JoepWi** [comment]
Can it be caused by a change how HA gets the info from the db. In the last monthly update a change is done (dunno what).
I just made a standard dashboard with all entities and that was also a bit slow on my app on the iphone.

**Comment by joakimjalden** [comment]
Full understanding @junalmeida that this will be an absolute bastard to debug, given that you do not experience the problem on your own platforms, but if it at all helps, I made a short screen recording of the problem using a test dashboard made by duplicating my regular cards. In this case, the actionable entities take a long time to load up, but the card does slow the whole tab down, which can be seen by the slow loading of icons in the side menu. The same dashboard loads instantly on my iPhone, both in the HA app and in the browser.

[Example youtube video](https://www.youtube.com/watch?v=lay7IADtuSI)

**Comment by richardwonka** [comment]
Can confirm. 

I have ten cards with at least ten entities each, ha 2023.4.2 and the dashboard is effectively unusable. 

Freezes about second after beginning to load, never to return.

**Comment by junalmeida** [comment]
I can see the issue happening on Mac Safari (2019 intel mbp running latest Ventura). However, when profiling the execution in Safari, I can see CPU spiking, but it does not indicate a problem with JS code, but with rendering itself it seems. 

When profiling in Chrome/Edge, I can see that it says it uses GPU to render, and it performs good. 

Please you all do add `shadow: false` to your test dashboards and see how it performs on both your MacOS and iOS devices. Thanks

**Comment by junalmeida** [comment]
![image](https://user-images.githubusercontent.com/991675/231495973-a83b8ea9-2cb3-4944-9519-aa439bc6fb97.png)

**Comment by pacoculebras** [comment]
> Please you all do add `shadow: false` to your test dashboards and see how it performs on both your MacOS and iOS devices. Thanks

With shadow: false it seems to work ok on my devices (HA app and Safari in iPhone and iPad).

**Comment by JoepWi** [comment]
> ![image](https://user-images.githubusercontent.com/991675/231495973-a83b8ea9-2cb3-4944-9519-aa439bc6fb97.png)

I changed all the cards on my main dashboard and it's responsive again in Safari and in the HA App on iOS.

**Comment by joakimjalden** [comment]
Late the game here, but "shadow: false" also fixes the issue in Safari for me.

**Comment by Remko76** [comment]
What I don’t understand yet is why it was no issue before. I mean... What has changed in Homeassistant causing this effect..?

**Comment by joakimjalden** [comment]
> What I don’t understand yet is why it was no issue before. I mean... What has changed in Homeassistant causing this effect..?

To add to the confusion, drop shadows, in general, do not seem to be problematic. I just made a dashboard with 21 picture cards with plenty of (text) drop shadows, and there is no difference in rendering speed between Safari and Chrome. Both are snappy.

**Comment by novus84** [comment]
everything works fine now with shadow: false
thank you!!

**Comment by junalmeida** [comment]
@Remko76 Not sure what exactly happened, if indeed it was this release that changed something, or just when people started to notice. It could be a mix of variables like how fast your computer/phone is, the number of cards and number of entities you have. 
What I've noticed is that somehow Safari is using the CPU to render shadows (which is a css filter attribute), and that's why it has a huge performance impact when you have many cards or entities. It doesn't seem to happen in Chrome/Edge and up-to-date Android phones though, but anyway, even if it uses GPU and becomes fast, I believe it could be a significant impact in battery usage.
