### ISSUE TITLE
Card fails to load with HACS install

### ISSUE THREAD

**Issue by j-steve** [junalmeida/homeassistant-minimalistic-area-card#7]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
"master" branch

**Last working release (if known):**
n/a

**Browser and Operating System:**
 Windows + Chrome; Mac + Chrome

**Description of problem:**

After installing this card from HACS, it fails to load in the dashboard, indicating that the card cannot be found.

This could potentially be related to the resource path it adds to the Dashboard config, which includes "null":
```/hacsfiles/homeassistant-minimalistic-area-card/null?hacstag=489457357```

**Javascript errors shown in the web inspector (if applicable):**

```
```[null:1] Failed to load resource: the server responded with a status of 404 (Not Found)```

```Uncaught (in promise) https://{{my domain}}/hacsfiles/homeassistant-minimalistic-area-card/null?hacstag=489457357
atomic-calendar-revive.js?hacstag=246549747620:70 
```

**Additional information:**
![2022-05-10 17_44_27-Overview – Home Assistant](https://user-images.githubusercontent.com/3261812/167727057-3a159cea-cfd7-4c09-8778-953c8814a1ae.png)

**Comment by junalmeida** [comment]
@j-steve could you please share your hacs and home assistant version? 
It is interesting because this card does not add any resource manually, this is expected to be managed/added by hacs itself.

**Comment by P1X3L8** [comment]
I'm seeing this too. Here are the only files installed in the community folder;

[core-ssh homeassistant-minimalistic-area-card]$ pwd
/config/www/community/homeassistant-minimalistic-area-card
[core-ssh homeassistant-minimalistic-area-card]$ ll
total 32
-rw-r--r--    1 root     root           611 May 10 10:33 .eslintrc.js
-rw-r--r--    1 root     root           346 May 10 10:33 .eslintrc.js.gz
-rw-r--r--    1 root     root           124 May 10 10:33 .prettierrc.js
-rw-r--r--    1 root     root           129 May 10 10:33 .prettierrc.js.gz
-rw-r--r--    1 root     root          1091 May 10 10:33 rollup.config.dev.js
-rw-r--r--    1 root     root           483 May 10 10:33 rollup.config.dev.js.gz
-rw-r--r--    1 root     root          1240 May 10 10:33 rollup.config.js
-rw-r--r--    1 root     root           564 May 10 10:33 rollup.config.js.gz


Missing minimalistic-area-card.js at a minimum. I tried reinstalling several times with the same result.

**Comment by j-steve** [comment]
Sure, here's my version info:
```
Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.1
Home Assistant OS 7.6
Kernel version 5.10.103-v8
Agent version 1.2.1
Path to configuration.yaml: /config
Frontend version: 20220504.1 - latest
HACS:
Integration version:  1.24.5
Frontend version:  20220401183545
```

My homeassistant-minimalistic-area-card directory has the same files mentioned by [P1X3L8](https://github.com/P1X3L8) and seems to be missing the minimalistic-area-card.js.

**Comment by junalmeida** [comment]
![image](https://user-images.githubusercontent.com/991675/168115634-90d59c9d-907b-443d-b5e4-a627242a710b.png)

This is what I see on my instance. It looks like a HACS issue? Could you try removing and readding, but watching hacs logs? They may have a way to see logs maybe?

**Comment by junalmeida** [comment]
Ah, also make sure hacs downloads the latest release `v1.0.5`. I haven't tested what happens if you force `master`. `v1.0.5` is the currently latest version and has the minified file, `master` won't have it.

**Comment by j-steve** [comment]
Ah that was the issue -- when I checked with HACS before the only branch option was "master", but now I'm seeing v1.0.5.  Loads fine now.

Thanks for the help, looking forward to trying out this card!
