### ISSUE TITLE
[Feature Request]: Let users defind state_image or state_filter for image 

### ISSUE THREAD

**Issue by djexplode6** [junalmeida/homeassistant-minimalistic-area-card#76]
### What happened?

I would like to define an entity and then use state filters to have the image b&w or color based on if that entity is on or off. Similar to how the picture glance card works.

### Card Version

1.1.16

### HomeAssistant Version

2023.4.5

**Comment by junalmeida** [comment]
@djexplode6 I believe you can use card-mod for custom css like that.
