### ISSUE TITLE
[Question]: Run automations

### ISSUE THREAD

**Issue by novus84** [junalmeida/homeassistant-minimalistic-area-card#79]
### What happened?

is it possible to run an automation? 
when I use "automation.xyz" like a switch, i can only switch the automation on/off. Same with lightscenes. 

Edit: 
its working with a helper switch, but is this the best solution? Or is it possible to trigger Automations directly?

### Card Version

1.1.16

### HomeAssistant Version

latest

**Comment by junalmeida** [comment]
I'm not sure if there is a way to do that as I don't see any push button entity directly related to automations, only on/off switches.
