### ISSUE TITLE
[Question]: Sensor precision ignored ?

### ISSUE THREAD

**Issue by SBRK** [junalmeida/homeassistant-minimalistic-area-card#87]
### What happened?

It seems the precision I set in the entity configuration is ignored in the card. I set a precision of 1 for all my temperature sensors, yet some sensors are displayed with a precision of 2 in the card

### Card Version

1.1.16

### HomeAssistant Version

2023.11.1

**Comment by fightingmajor** [comment]
Any update on this?

**Comment by CaixaNegraPT** [comment]
I thought the issue was something on my side but looks like it is a bug? :( is this planned to be addressed?

**Comment by bigbadoooff** [comment]
same problem here. I have temperature sensors in minimalistic area cards with 13 digits and no means to adjust this.

**Comment by junalmeida** [comment]
This is a dupe of #59 #78
