### ISSUE TITLE
[Question]: Enable users to exclude devices from the auto-discovered list

### ISSUE THREAD

**Issue by MarkTarry** [junalmeida/homeassistant-minimalistic-area-card#92]
### What happened?

When the `entities` field is omitted, the card auto-discovers entities in an area 👍 

It would be useful to allow users to explicitly exclude certain entities, while retaining the ability to auto-discover all other devices in the area.

For example, on my front-drive I have an EV charger - which is integrated with HA, and has quite a lot of entities:
![image](https://github.com/junalmeida/homeassistant-minimalistic-area-card/assets/155492324/ad314ead-ed20-447d-9c30-bc97b67d6c46)

It would be great if I could exclude some of these, while the card continues to auto-discover any new entities which I add to this area in future.

### Card Version

1.1.16

### HomeAssistant Version

Core - 2024.1.2

**Comment by junalmeida** [comment]
@MarkTarry you can exclude entities by toggling off the "Visible" toggle. 
![image](https://github.com/junalmeida/homeassistant-minimalistic-area-card/assets/991675/2e9ef42a-aab0-45aa-af37-59222fb9dd0d)

**Comment by TheTarry** [comment]
> you can exclude entities by toggling off the "Visible" toggle. !

Agreed, this is an option. But it also marks the entity Hidden across the entire Home Assistant instance. I'm suggesting a feature that allows users to exclude specific entities only from these area cards.
