### ISSUE TITLE
[Question]: Card without entities

### ISSUE THREAD

**Issue by Kfrard** [junalmeida/homeassistant-minimalistic-area-card#95]
### What happened?

Hi, I would like to make it possible for the card not to show any entities (or to choose to show only those with temperature).

### Card Version

1.1.16

### HomeAssistant Version

2024.2.1

**Comment by SteeledKnight** [comment]
+1
I have a couple of areas that don't currently have any entities that I want to show.

**Comment by SteeledKnight** [comment]
@Kfrard 
Update: I found a work-around to show no entities:

`        hide_unavailable: true
        tap_action:
          action: navigate
          navigation_path: /config/areas/area/bathroom
        entities:
          - none`
