### ISSUE TITLE
Limit to n decimal places

### ISSUE THREAD

**Issue by chris-y** [junalmeida/homeassistant-minimalistic-area-card#96]
### What happened?

I have a router which I can add download speed to this card. However it adds as many decimal places.
Elsewhere in HA it is set to one decimal place but the card doesn't appear to respect this:
![Screenshot_20240324-192518-564](https://github.com/junalmeida/homeassistant-minimalistic-area-card/assets/1818803/573a74b8-2f0f-4490-99d4-f7aa9600984b)

(Top is the default area card, bottom is this minimalistic one)

### Card Version

1.1.16

### HomeAssistant Version

2024.3.3

**Comment by floco** [comment]
looks like a duplicate to https://github.com/junalmeida/homeassistant-minimalistic-area-card/issues/59
But this would be a great feature.
