### ISSUE TITLE
Area Icon

### ISSUE THREAD

**Issue by ncodee** [junalmeida/homeassistant-minimalistic-area-card#98]
### What happened?

Could we get option to add Area icon next to the title header?

Thanks

### Card Version

Latest

### HomeAssistant Version

Latest

**Comment by ncodee** [comment]
Any progress on this? @ManuelW77 @junalmeida

**Comment by oerix** [comment]
Bump, please add

**Comment by LesTR** [comment]
@oerix something like this? https://github.com/LesTR/homeassistant-minimalistic-area-card/pull/2

**Comment by oerix** [comment]
> @oerix something like this? [LesTR#2](https://github.com/LesTR/homeassistant-minimalistic-area-card/pull/2)

Oh wow, that was fast! Thank you so much. 😁

**Comment by LesTR** [comment]
I merged and released it in my fork. I would like to contribute it back, but I already have opened 2 PRs, and it's hard to keep them up-to-date. I'll try to do that when I get some feedback from @junalmeida for those first 2.
